version: '3.5'
x-logging:
    &es-logging
    options:
      max-size: '100m'
      max-file: '10'
    driver: json-file

services:
  elasticsearch:
    image: registry.cn-shenzhen.aliyuncs.com/baoping/elasticsearch:lts
    # image: registry.cn-shenzhen.aliyuncs.com/django-blog/elasticsearch:lts
    # image: elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - cluster.name=cedb-es-release
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"  # 服务器内存太小 此处修改为1024
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - esdata1:/usr/share/elasticsearch/data  # 需编译镜像自己创建该文件
    ports:
      - 9200:9200
    networks:
      - esnet
    logging: *es-logging
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
  kibana:
    # build: 
    #   context: ./
    image: registry.cn-shenzhen.aliyuncs.com/django-blog/kibana:6.6.2
    # image: kibana:6.6.2
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - esnet
    logging: *es-logging
    depends_on:
      - "elasticsearch"
    restart: on-failure
    command: /bin/bash -c "sleep 10 && echo 'Run - '`date` && kibana-docker"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
